# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-03 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSession',
            fields=[
                ('session_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('started_by', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField()),
                ('summary_status', models.CharField(max_length=50)),
                ('duration', models.FloatField()),
                ('worker_time', models.FloatField()),
                ('bundle_time', models.PositiveIntegerField()),
                ('num_workers', models.PositiveSmallIntegerField()),
                ('branch', models.CharField(max_length=200)),
                ('commit_id', models.CharField(max_length=200)),
                ('started_tests_count', models.PositiveIntegerField(default=0)),
                ('passed_tests_count', models.PositiveIntegerField()),
                ('failed_tests_count', models.PositiveIntegerField()),
                ('pending_tests_count', models.PositiveIntegerField()),
                ('skipped_tests_count', models.PositiveIntegerField()),
                ('error_tests_count', models.PositiveIntegerField()),
            ],
        ),
    ]
